name: Discord Notifier

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main

jobs: 
  discord-notifier:
    - name: Discord Notifier
      # You may pin to the exact commit or the version.
      # uses: fateyan/action-discord-notifier@2d543d3e7e2c63546420b10f2652cb61e24578fc
      uses: fateyan/action-discord-notifier@v1.2.0
      with:
        # A full discord webhook url
        webhook: https://discord.com/api/webhooks/794085360018784266/2bxYb3qP1h22i1gkEQbKkh60vUW1WRC2Gzz8l4VESaDv1w-LOupZXQLToKCYK7Y6h2Pf
        # Message title
        message-title: # optional
