name: Discord Notifier

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main

jobs: 
  discord-notifier:
    name: Discord Notifier
      uses: fateyan/action-discord-notifier@v1.2.0
      with:
        webhook: https://discord.com/api/webhooks/794085360018784266/2bxYb3qP1h22i1gkEQbKkh60vUW1WRC2Gzz8l4VESaDv1w-LOupZXQLToKCYK7Y6h2Pf
        message-title: # optional
